
import Head from 'next/head'
import { FaShoppingCart } from 'react-icons/fa';

import Image from 'next/image'
import styles from '../styles/Home.module.css'
import {useCart} from '../hooks/use-cart'
import products from '../products.json'

export default function Home() {
  const {subtotal, quantity, addToCart, checkout  } = useCart()

  return (
    <div className={styles.container}>
      <Head>
        <title>T-shirt Hub</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        {/* <ul className={styles.grid}>
          {products.map(product=>{
            const{title, price, description, image, id} = product
            return (
              <li className={styles.card} key={id}>
                <a href="#">
                  <img src={image} alt={title} height="300"/>
                  <h2>{title}</h2>
                  <p>Rs.{price}</p>
                  <p>{description}</p>
                  <p>
                    <button className={styles.button} onClick={()=>addToCart({id})
                    
                    }>Add to Cart</button>
                  </p>
                </a>
              </li>
            )
          })}
        </ul> */}
        <ul className={styles.cards}>
          {products.map(product=>{
            const{title, price, description, image, id} = product
            return (
              <li key={id}  className={styles.card}>
                  <img src={image} alt={title} />
                  <h2>{title}</h2>
                  <p className={styles.price}>Rs.{price}</p>
                  <p>{description}</p>
                  <p><button className={styles.button} onClick={()=>addToCart({id})
                    
                    }>Add to Cart</button>
                  </p>
              </li>
            )
          })}
        </ul>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}
