import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import products from '../products.json'
import {initiateCheckout} from '../lib/payment'
export default function Home() {
  console.log(products)
  console.log(process.env.NEXT_PUBLIC_STRIPE_API_AKEY)
  return (
    <div className={styles.container}>
      <Head>
        <title>Programmers T-shirt Hub</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Programmers T-shirt Hub
        </h1>

        <p className={styles.description}>
         The best place to buy Programmers swag on the web!
        </p>

        <ul className={styles.grid}>
          {products.map(product=>{
            const{title, price, description, image, id} = product
            return (
              <li className={styles.card} key={id}>
                <a href="#">
                  <img src={image} alt={title} height="300"/>
                  <h2>{title}</h2>
                  <p>Rs.{price}</p>
                  <p>{description}</p>
                  <p>
                    <button className={styles.button} onClick={()=>initiateCheckout({
                      lineItems:[
                        {
                          price:id,
                          quantity:1
                        }
                      ]
                    })}>Buy Now</button>
                  </p>
                </a>
              </li>
            )
          })}
        </ul>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}
