import {useEffect} from 'react'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Thanks.module.css'


export default function Thanks() {
    useEffect(() => {
        window.localStorage.clear()
    }, [])
  return (
    <div className={styles.container}>
      <Head>
        <title>Thank You - T-shirt Hub</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <header className={styles.header}>
            <h1>THANK YOU!</h1>
        </header>

        <div className={styles.description}>
            <p class="main-content__body" data-lead-id="main-content-body">Thank you very much for ordering from us. We will email you as soon as this order ships.</p>
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}
